### ISSUE TITLE
1.8 builds are incomplete.

### ISSUE THREAD

**Issue by mhils** [dojo/dwb#17]
Hello there,

When replacing a full dojo release with the custom build, I get two 404 errors for

http://localhost:8081/app/js/lib/dojo/themes/dijit.css
http://localhost:8081/app/js/lib/dojo/icons/commonIcons.css

These files seem to be missing.

My build includes the following components:
dojo.query  dijit.layout.BorderContainer    dijit.layout.TabContainer dijit.layout.ContentPane dojo.domReady    

Thanks!

**Comment by jthomas** [comment]
Thanks for reporting this issue, 
I've found the issue and put a fix in for the problems you were describing, can you try again? 

Re-open the ticket if you're still having problems.
