### ISSUE TITLE
The builded '\uFFFF$1\uFFFF' ==> "$1" is not working in IE9

### ISSUE THREAD

**Issue by hNczy** [dojo/dwb#26]
Dear DWB Team!

I found a problem whit my build (dojo 1.8). If the dijit/form/_AutoComleterMixin.js is in the build, in doHighlight function return command is bad.

In my build:
return this._escapeHtml(_529.replace(new RegExp((i==0?"^":"")+"("+find+")"+(i==(this.queryExpr.length-4)?"$":""),_52a),"￿$1￿")).replace(/\uFFFF([^\uFFFF]+)\uFFFF/g,"<span class=\"dijitComboBoxHighlightMatch\">$1</span>");

Original from src Line-515:
return this._escapeHtml(label.replace(
                new RegExp((i == 0 ? "^" : "") + "("+ find +")" + (i == (this.queryExpr.length - 4) ? "$" : ""), modifiers),
                '\uFFFF$1\uFFFF')).replace(
                    /\uFFFF([^\uFFFF]+)\uFFFF/g, '<span class="dijitComboBoxHighlightMatch">$1</span>'
            );

The builded '\uFFFF$1\uFFFF' ==> "￿$1￿" string is the problem.
In IE9 the highlight is not working. I see "￿find￿outer text". In FireFox i dont have problem. If I replace in builded dojo.js the string, then working in IE9 too. 

hNczy

**Comment by ghost** [comment]
This was a ShrinkSafe bug already fixed in Dojo 1.8.1.

Doug Hays

**Comment by hNczy** [comment]
Ok THX! When will be available the new version on dwb?

**Comment by jthomas** [comment]
I've updated the version of shrinksafe in the tool, this should be working now!
