### ISSUE TITLE
Image files are corrupted

### ISSUE THREAD

**Issue by joacim-boive** [dojo/dwb#7]
Really great tool! But the image files (.gif and .png) included with the build are corrupt somehow.

You can't open them in a browser or Photoshop.

Steps to reproduce:

Use the defaults
Just pick the dijit.Calendar
Build
Download
Try and open an image.

Filesize and everything looks right but they're corrupt.

I tried building in both Chrome 19 and Safari 5 on OS X Lion.

Here's a sample of a corrupt .png-file: http://dl.dropbox.com/u/9681254/accordion.png

**Comment by jthomas** [comment]
Hey, 

Thanks for reporting this! We're unfortunately aware of this issue and it's an artefact of the build system in the backend. This will be cleared up as I move the tool to the new Dojo 1.7 build system over the next few months. 

I'll leave this open and close it out as it's fixed.

**Comment by jthomas** [comment]
This should be fixed now, can you re-try and re-open if it isn't? 

Thanks!
